
package co.manager.b1ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginServiceSoap", targetNamespace = "LoginService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginServiceSoap {


    /**
     * 
     * @param databaseType
     * @param companyPassword
     * @param databaseServer
     * @param databaseName
     * @param companyUsername
     * @param language
     * @param licenseServer
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login", action = "LoginService/Login")
    @WebResult(name = "SessionID", targetNamespace = "http://www.sap.com/SBO/DIS")
    @RequestWrapper(localName = "Login", targetNamespace = "LoginService", className = "co.igb.b1ws.client.login.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://www.sap.com/SBO/DIS", className = "co.igb.b1ws.client.login.LoginResponse")
    public String login(
        @WebParam(name = "DatabaseServer", targetNamespace = "LoginService")
        String databaseServer,
        @WebParam(name = "DatabaseName", targetNamespace = "LoginService")
        String databaseName,
        @WebParam(name = "DatabaseType", targetNamespace = "LoginService")
        String databaseType,
        @WebParam(name = "CompanyUsername", targetNamespace = "LoginService")
        String companyUsername,
        @WebParam(name = "CompanyPassword", targetNamespace = "LoginService")
        String companyPassword,
        @WebParam(name = "Language", targetNamespace = "LoginService")
        String language,
        @WebParam(name = "LicenseServer", targetNamespace = "LoginService")
        String licenseServer);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.igb.b1ws.client.login.LogoutResponse
     */
    @WebMethod(operationName = "Logout", action = "LoginService/Logout")
    @WebResult(name = "LogoutResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public LogoutResponse logout(
        @WebParam(name = "Logout", targetNamespace = "LoginService", partName = "parameters")
        Logout parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

}
